# Generated by Django 4.2.9 on 2024-01-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
