# Generated by Django 4.2.9 on 2024-01-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='qr_code',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
